# NumPy 2D array

In [ ]:
#Problem Statement: Given a 2D list, create a numpy 2D array using it.
# Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# Print the Numpy array.

#Output Format :numpyArray

In [ ]:
import numpy as np
print(np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

# NumPy 0s and 1s

In [1]:
#Problem Statement:
#Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
#Print the elements of array.

In [ ]:
import numpy as np
l=np.zeros(10)
l[5-1]=1
for i in l:
    print(int(i),end=' ')

# NumPy Inclusive

In [2]:
#Problem Statement:
#Create an array with values ranging consecutively from 9 to 49 (both inclusive).
#Print the Numpy array.

In [ ]:
import numpy as np
a = np.arange(9,49+1)
for i in a:
    print(i,end=' ')

# Identity Matrix

In [3]:
#Problem Statement:
#Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).
#Print the Numpy array.

In [ ]:
import numpy as np
a=np.eye(5,6,dtype=int)
print(a)

# Cut the Rope

In [4]:
#Problem Statement:
#You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
#Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
#Print the array element.

In [ ]:
import numpy as np
a = np.linspace(0,5,10)[1:9]
for i in a:
    print(round(i,2))

# Print Elements

In [5]:
#Problem Statement:
#Given a 2D integer array size (4, 5) with name input_?
#Print elements of highlighted matrix

In [ ]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
for i in input_[2,:3]:
    print(i,end=' ')
print()
for i in input_[1:,3]:
    print(i,end=' ')
print()
for i in input_[2:]:
    for j in i:
        print(j,end=' ')
print()
for i in input_[1:3,1:3]:
    for j in i:
        print(j,end=' ')

# Non-Zero elements

In [6]:
#Problem Statemnt:
#Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
#Print the index of non-zero elements.

In [ ]:
import numpy as np
l=np.array([1,2,0,0,4,0])
m=np.where(l!=0)
#print(m)
for j in m:
    for i in j:
        print(i ,end=' ')

# Multiples of 3

In [7]:
#Problem Statement:
#Given an integer array of size 10. Print the index of elements which are multiple of 3.
#Note: Generate the following array
#array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
#Print the index of elements.


In [ ]:
import numpy as np
l=np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
k=np.where(l%3==0)
for i in k:
    for j in i:
        print(j,end=' ')

# Odd elements

In [8]:
#Problem Statemnt:
#Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
#Note: Generate the following array
#array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#Print the Numpy array.

In [ ]:
import numpy as np
l=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
l[l%2!=0]=-1

for i in l:
    print(i,end=' ')

# Replace Max

In [ ]:
#Problem Statemnt:
#Given an integer array of size 9 and replace the first occurrence of maximum value by 0?
#Note: Generate the following array
#array([11, 2, 13, 4, 15, 6, 27, 8, 19])
#Print the Numpy array.

In [ ]:
import numpy as np
l=np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
l[np.argmax(l)]=0
for i in l:
    print(i)

# Negate Elements

In [9]:
#Problem Statemnt:
#Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
#Note: Generate the following array
#array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#Print the Numpy array.

In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(arr>=3)&(arr<=8)]*=-1
for i in arr:
    print(i)

# Height

In [10]:
#Problem Statemnt:
#Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
#Print the Numpy array.

In [ ]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
l=height > 155
k1=age[l]
k2=height[l]

for i in range(len(k1)):
    print(k1[i],k2[i])

# Sort by column

In [ ]:
#Problem Statemnt:
#Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
#That means, we should re-arrange complete row based on 2nd columns' values.
#Given 2D array is:
# [[21 20 19 18 17]
#  [16 15 14 13 12]
#  [11 10  9  8  7]
#  [ 6  5  4  3  2]]
#Print the 2D array in sorted order.
#Note you have to generate the 2D Array.Here 2nd column means column present at index 1.

In [ ]:
import numpy  as np
l=np.array( [[21 ,20, 19, 18, 17],
  [16 ,15 ,14 ,13 ,12],
  [11 ,10,  9 , 8 , 7],
  [ 6  ,5  ,4  ,3  ,2]])
k=np.sort(l,axis=0)
print(k)

# Killed in USA

In [11]:
#Given file "terrorismData.csv"
#It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
#Problem Statement :
#Find value of killed column only where country == ‘United States’?
#Print 0 in place of missing values.
#Print count of Killed as integer value.

In [ ]:
import numpy as np
import csv
l=open('terrorismData.csv','r')
file=csv.DictReader(l,skipinitialspace=True)
a=[]
b=[]
for i in file:
    a.append(i['Country'])
    b.append(i['Killed'])
country=np.array(a)
kill=np.array(b)
L=country=='United States'
kill[kill=='']='0.0'
kill=np.array(kill,dtype=float)
kill=np.array(kill,dtype=int)
res1=kill[L]
res2=country[L]
for i in res1:
    print(i)


# Total Killed in USA

In [12]:
#Given file "terrorismData.csv"
#It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
#Problem Statement :
#Find total number of people killed from USA?
#Note: Some columns of killed are empty so replace them by 0.
#Print count of Killed as integer value.

In [ ]:
import numpy as np
import csv

file=open("terrorismData.csv")
data=csv.DictReader(file,skipinitialspace=True)
killed=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    
np_killed=np.array(killed)
np_killed[np_killed=='']='0.0'

np_killed=np.array(np_killed,dtype=float)
np_country=np.array(country)
b=np_country=='United States'
ans=np_killed[b]

print(int(np.sum(ans)))